# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
    - name: 1. Check out repository code
      uses: actions/checkout@v4

    - name: 2. Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: 3. Install dependencies
      shell: bash
      run: |
        python -m venv .venv
        if [ "$RUNNER_OS" == "Windows" ]; then
          . .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        pip install -r requirements.txt
        pip install ruff

    

    - name: 5. Basic Streamlit run test (Check if it starts)
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          . .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        streamlit --version
